title: project
pages: false
files:
  sortable: true
fields:
  title:
    label: Title
    type: title
  text:
    label: Text
    type: textarea
  year:
    label: Year
    type: date
    width: 1/2
  website:
    label: Website
    type: url
    width: 1/2
  